Vagrant.configure("2") do |config|
	(1..2).each do |i|
		if i == 1
			# First VM --> Control Plane
			config.vm.define "control_plane" do |node|
				node.vm.box = "ubuntu/focal64"
				node.vm.hostname = "control-plane"
				node.vm.network "private_network", ip: "192.168.56.10"
				node.vm.provider "virtualbox" do |vb|
					vb.memory = "3076"
					vb.cpus = 2
				end
				node.vm.provision "shell", path: "cp.sh"
			end
		else
			# Worker Nodes
			config.vm.define "worker#{i-1}" do |node|
				node.vm.box = "ubuntu/focal64"
				node.vm.hostname = "worker#{i-1}"
				node.vm.network "private_network", ip: "192.168.56.1#{i}"
				node.vm.provider "virtualbox" do |vb|
					vb.memory = "2048"
					vb.cpus = 2
				end
				node.vm.provision "shell", path: "worker.sh"
			end
		end
	end
end